
{ config, pkgs, ... }:

let
  home-manager = builtins.fetchTarball https://github.com/nix-community/home-manager/archive/master.tar.gz;
in

{
  imports =
    [ # Include the results of the hardware scan.
      ./hardware-configuration.nix
      (import "${home-manager}/nixos")
      # /home/jr/.config/home-manager/home.nix
  ];

  home-manager.backupFileExtension = "bak";
  home-manager.users.jr = { pkgs, ... }: {
    home.packages = with pkgs; [ 
      
    ]; 

    home.file = {

      # ".config/nixpkgs/config.nix" = {
      #   text = ''
      #     allowUnfree = true;
      #   '';
      # };
      
      ".bashrc" = {
        text = ''
          LIVE_COUNTER=$(ps a | awk '{print $2}' | grep -vi "tty*" | uniq | wc -l);
          if [ $LIVE_COUNTER -eq 1 ]; then
            fastfetch
          fi

          eval "$(starship init bash)"
        '';
      };

      "code-flags.conf" = {
        text = ''
          --ozone-platform=wayland
        '';
      };
      
      ".config/fastfetch/config.jsonc" = {
        text = ''
              {
          "$schema": "https://github.com/fastfetch-cli/fastfetch/raw/dev/doc/json_schema.json",
          "modules": [
            "title",
            "separator",
            "uptime",
            "host",
            "os",
            "kernel",
            "packages",
            "de",
            "wm",
            // "wmtheme",
            // "theme",
            // "icons",
            // "font",
            // "cursor",
            "terminal",
            // "terminalfont",
            "shell",
            "display",
            "cpu",
            "gpu",
            "memory",
            // "swap",
            "disk",
            // "localip",
            "publicip",
            "battery",
            "poweradapter",
            // "locale",
            "break",
            "colors"
          ]
        }
      '';
      };
    
      ".config/hypr/hyprland.conf" = {
        text = ''
          # #######################################################################################
          # AUTOGENERATED HYPR CONFIG.
          # PLEASE USE THE CONFIG PROVIDED IN THE GIT REPO /examples/hypr.conf AND EDIT IT,
          # OR EDIT THIS ONE ACCORDING TO THE WIKI INSTRUCTIONS.
          # #######################################################################################

          autogenerated = 0 # remove this line to remove the warning

          # This is an example Hyprland config file.
          # Refer to the wiki for more information.
          # https://wiki.hyprland.org/Configuring/

          # Please note not all available settings / options are set here.
          # For a full list, see the wiki

          # You can split this configuration into multiple files
          # Create your files separately and then link them to this file like this:
          # source = ~/.config/hypr/myColors.conf


          ################
          ### MONITORS ###
          ################

          # See https://wiki.hyprland.org/Configuring/Monitors/
          monitor = eDP-1,highres,auto,1


          ###################
          ### MY PROGRAMS ###
          ###################

          # See https://wiki.hyprland.org/Configuring/Keywords/

          # Set programs that you use
          $terminal = kitty
          $fileManager = dolphin
          $menu = wofi --show drun


          #################
          ### AUTOSTART ###
          #################

          # Autostart necessary processes (like notifications daemons, status bars, etc.)
          # Or execute your favorite apps at launch like this:

          # exec-once = 
          exec-once = conky &
          exec-once = hyprpaper &


          #############################
          ### ENVIRONMENT VARIABLES ###
          #############################

          # See https://wiki.hyprland.org/Configuring/Environment-variables/

          env = XCURSOR_SIZE,24
          env = HYPRCURSOR_SIZE,24


          #####################
          ### LOOK AND FEEL ###
          #####################

          # Refer to https://wiki.hyprland.org/Configuring/Variables/

          # https://wiki.hyprland.org/Configuring/Variables/#general
          general {
              gaps_in = 5
              gaps_out = 5

              border_size = 2

              # https://wiki.hyprland.org/Configuring/Variables/#variable-types for info about colors
              col.active_border = rgba(33ccffee) rgba(00ff99ee) 45deg
              col.inactive_border = rgba(595959aa)

              # Set to true enable resizing windows by clicking and dragging on borders and gaps
              resize_on_border = false

              # Please see https://wiki.hyprland.org/Configuring/Tearing/ before you turn this on
              allow_tearing = false

              layout = dwindle
          }

          # https://wiki.hyprland.org/Configuring/Variables/#decoration
          decoration {
              rounding = 10

              # Change transparency of focused and unfocused windows
              active_opacity = 1.0
              inactive_opacity = 0.9

              shadow {
                  enabled = false
                  range = 4
                  render_power = 3
                  color = rgba(1a1a1aee)
              }

              # https://wiki.hyprland.org/Configuring/Variables/#blur
              blur {
                  enabled = false
                  size = 3
                  passes = 1

                  vibrancy = 0.1696
              }
          }

          # https://wiki.hyprland.org/Configuring/Variables/#animations
          animations {
              enabled = yes, please :)

              # Default animations, see https://wiki.hyprland.org/Configuring/Animations/ for more

              bezier = easeOutQuint,0.23,1,0.32,1
              bezier = easeInOutCubic,0.65,0.05,0.36,1
              bezier = linear,0,0,1,1
              bezier = almostLinear,0.5,0.5,0.75,1.0
              bezier = quick,0.15,0,0.1,1

              animation = global, 1, 10, default
              animation = border, 1, 5.39, easeOutQuint
              animation = windows, 1, 4.79, easeOutQuint
              animation = windowsIn, 1, 4.1, easeOutQuint, popin 87%
              animation = windowsOut, 1, 1.49, linear, popin 87%
              animation = fadeIn, 1, 1.73, almostLinear
              animation = fadeOut, 1, 1.46, almostLinear
              animation = fade, 1, 3.03, quick
              animation = layers, 1, 3.81, easeOutQuint
              animation = layersIn, 1, 4, easeOutQuint, fade
              animation = layersOut, 1, 1.5, linear, fade
              animation = fadeLayersIn, 1, 1.79, almostLinear
              animation = fadeLayersOut, 1, 1.39, almostLinear
              animation = workspaces, 1, 1.94, almostLinear, fade
              animation = workspacesIn, 1, 1.21, almostLinear, fade
              animation = workspacesOut, 1, 1.94, almostLinear, fade
          }

          # Ref https://wiki.hyprland.org/Configuring/Workspace-Rules/
          # "Smart gaps" / "No gaps when only"
          # uncomment all if you wish to use that.
          # workspace = w[tv1], gapsout:0, gapsin:0
          # workspace = f[1], gapsout:0, gapsin:0
          # windowrulev2 = bordersize 0, floating:0, onworkspace:w[tv1]
          # windowrulev2 = rounding 0, floating:0, onworkspace:w[tv1]
          # windowrulev2 = bordersize 0, floating:0, onworkspace:f[1]
          # windowrulev2 = rounding 0, floating:0, onworkspace:f[1]

          # See https://wiki.hyprland.org/Configuring/Dwindle-Layout/ for more
          dwindle {
              pseudotile = true # Master switch for pseudotiling. Enabling is bound to mainMod + P in the keybinds section below
              preserve_split = true # You probably want this
          }

          # See https://wiki.hyprland.org/Configuring/Master-Layout/ for more
          master {
              new_status = master
          }

          # https://wiki.hyprland.org/Configuring/Variables/#misc
          misc {
              force_default_wallpaper = 0 # Set to 0 or 1 to disable the anime mascot wallpapers
              disable_hyprland_logo = true # If true disables the random hyprland logo / anime girl background. :(
              vfr = true
          }


          #############
          ### INPUT ###
          #############

          # https://wiki.hyprland.org/Configuring/Variables/#input
          input {
              kb_layout = dk
              kb_variant =
              kb_model =
              kb_options =
              kb_rules =

              numlock_by_default = true

              follow_mouse = 1

              sensitivity = 0 # -1.0 - 1.0, 0 means no modification.

              touchpad {
                  natural_scroll = false
              }
          }

          # https://wiki.hyprland.org/Configuring/Variables/#gestures
          gestures {
              workspace_swipe = false
          }

          # Example per-device config
          # See https://wiki.hyprland.org/Configuring/Keywords/#per-device-input-configs for more
          device {
              name = epic-mouse-v1
              sensitivity = -0.5
          }


          ###################
          ### KEYBINDINGS ###
          ###################

          # See https://wiki.hyprland.org/Configuring/Keywords/
          $mainMod = SUPER # Sets "Windows" key as main modifier

          # Example binds, see https://wiki.hyprland.org/Configuring/Binds/ for more
          bind = $mainMod, Q, exec, $terminal
          bind = $mainMod, C, killactive,
          bind = $mainMod, M, exit,
          bind = $mainMod, E, exec, $fileManager
          bind = $mainMod SHIFT, E, exec, doublecmd
          bind = $mainMod, V, togglefloating,
          bind = $mainMod, R, exec, $menu
          bind = $mainMod, P, pseudo, # dwindle
          bind = $mainMod, J, togglesplit, # dwindle

          # Move focus with mainMod + arrow keys
          bind = $mainMod, left, movefocus, l
          bind = $mainMod, right, movefocus, r
          bind = $mainMod, up, movefocus, u
          bind = $mainMod, down, movefocus, d

          # Move window with mainMod + shift + arrow keys
          bind = $mainMod SHIFT, left, movewindow, l
          bind = $mainMod SHIFT, right, movewindow, r
          bind = $mainMod SHIFT, up, movewindow, u
          bind = $mainMod SHIFT, down, movewindow, d

          # Switch workspaces with mainMod + [0-9]
          bind = $mainMod, 1, workspace, 1
          bind = $mainMod, 2, workspace, 2
          bind = $mainMod, 3, workspace, 3
          bind = $mainMod, 4, workspace, 4
          bind = $mainMod, 5, workspace, 5
          bind = $mainMod, 6, workspace, 6
          bind = $mainMod, 7, workspace, 7
          bind = $mainMod, 8, workspace, 8
          bind = $mainMod, 9, workspace, 9
          bind = $mainMod, 0, workspace, 10

          # Move active window to a workspace with mainMod + SHIFT + [0-9]
          bind = $mainMod SHIFT, 1, movetoworkspace, 1
          bind = $mainMod SHIFT, 2, movetoworkspace, 2
          bind = $mainMod SHIFT, 3, movetoworkspace, 3
          bind = $mainMod SHIFT, 4, movetoworkspace, 4
          bind = $mainMod SHIFT, 5, movetoworkspace, 5
          bind = $mainMod SHIFT, 6, movetoworkspace, 6
          bind = $mainMod SHIFT, 7, movetoworkspace, 7
          bind = $mainMod SHIFT, 8, movetoworkspace, 8
          bind = $mainMod SHIFT, 9, movetoworkspace, 9
          bind = $mainMod SHIFT, 0, movetoworkspace, 10

          # Example special workspace (scratchpad)
          bind = $mainMod, S, togglespecialworkspace, magic
          bind = $mainMod SHIFT, S, movetoworkspace, special:magic

          # Scroll through existing workspaces with mainMod + scroll
          bind = $mainMod, mouse_down, workspace, e+1
          bind = $mainMod, mouse_up, workspace, e-1

          # Move/resize windows with mainMod + LMB/RMB and dragging
          bindm = $mainMod, mouse:272, movewindow
          bindm = $mainMod, mouse:273, resizewindow

          # Laptop multimedia keys for volume and LCD brightness
          bindel = ,XF86AudioRaiseVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+
          bindel = ,XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
          bindel = ,XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
          bindel = ,XF86AudioMicMute, exec, wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle
          bindel = ,XF86MonBrightnessUp, exec, brightnessctl s 10%+
          bindel = ,XF86MonBrightnessDown, exec, brightnessctl s 10%-

          # Requires playerctl
          bindl = , XF86AudioNext, exec, playerctl next
          bindl = , XF86AudioPause, exec, playerctl play-pause
          bindl = , XF86AudioPlay, exec, playerctl play-pause
          bindl = , XF86AudioPrev, exec, playerctl previous

          # Application launchers
          bind = $mainMod, XF86AudioMute, exec, codium --ozone-platform=wayland
          bind = $mainMod, XF86AudioLowerVolume, exec, brave
          # bind = $mainMod, XF86AudioRaiseVolume, exec, 
          bind = $mainMod, XF86AudioMicMute, exec, virt-manager

          ##############################
          ### WINDOWS AND WORKSPACES ###
          ##############################

          # See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
          # See https://wiki.hyprland.org/Configuring/Workspace-Rules/ for workspace rules

          # Example windowrule v1
          # windowrule = float, ^(kitty)$

          # Example windowrule v2
          # windowrulev2 = float,class:^(kitty)$,title:^(kitty)$

          # Ignore maximize requests from apps. You'll probably like this.
          windowrulev2 = suppressevent maximize, class:.*

          # Fix some dragging issues with XWayland
          windowrulev2 = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0

        '';
      }; 

      ".config/kitty/kitty.conf" = {
        text = ''
          confirm_os_window_close 0

          font_family FiraCodeNerdFont
        '';
      };       

      ".config/mc/ini" = {
        text = ''
          [Midnight-Commander]
          verbose=true
          shell_patterns=true
          auto_save_setup=true
          preallocate_space=false
          auto_menu=false
          use_internal_view=true
          use_internal_edit=true
          clear_before_exec=true
          confirm_delete=true
          confirm_overwrite=true
          confirm_execute=false
          confirm_history_cleanup=true
          confirm_exit=false
          confirm_directory_hotlist_delete=false
          confirm_view_dir=false
          safe_delete=false
          safe_overwrite=false
          use_8th_bit_as_meta=false
          mouse_move_pages_viewer=true
          mouse_close_dialog=false
          fast_refresh=false
          drop_menus=false
          wrap_mode=true
          old_esc_mode=true
          cd_symlinks=true
          show_all_if_ambiguous=false
          use_file_to_guess_type=true
          alternate_plus_minus=false
          only_leading_plus_minus=true
          show_output_starts_shell=false
          xtree_mode=false
          file_op_compute_totals=true
          classic_progressbar=true
          use_netrc=true
          ftpfs_always_use_proxy=false
          ftpfs_use_passive_connections=true
          ftpfs_use_passive_connections_over_proxy=false
          ftpfs_use_unix_list_options=true
          ftpfs_first_cd_then_ls=true
          ignore_ftp_chattr_errors=true
          editor_fill_tabs_with_spaces=false
          editor_return_does_auto_indent=true
          editor_backspace_through_tabs=false
          editor_fake_half_tabs=true
          editor_option_save_position=true
          editor_option_auto_para_formatting=false
          editor_option_typewriter_wrap=false
          editor_edit_confirm_save=true
          editor_syntax_highlighting=true
          editor_persistent_selections=true
          editor_drop_selection_on_copy=true
          editor_cursor_beyond_eol=false
          editor_cursor_after_inserted_block=false
          editor_visible_tabs=true
          editor_visible_spaces=true
          editor_line_state=false
          editor_simple_statusbar=false
          editor_check_new_line=false
          editor_show_right_margin=false
          editor_group_undo=false
          editor_state_full_filename=false
          editor_ask_filename_before_edit=false
          nice_rotating_dash=true
          shadows=true
          mcview_remember_file_position=false
          auto_fill_mkdir_name=true
          copymove_persistent_attr=true
          pause_after_run=1
          mouse_repeat_rate=100
          double_click_speed=250
          old_esc_mode_timeout=1000000
          max_dirt_limit=10
          num_history_items_recorded=60
          vfs_timeout=60
          ftpfs_directory_timeout=900
          ftpfs_retry_seconds=30
          shell_directory_timeout=900
          editor_tab_spacing=8
          editor_word_wrap_line_length=72
          editor_option_save_mode=0
          editor_backup_extension=~
          editor_filesize_threshold=64M
          editor_stop_format_chars=-+*\\,.;:&>
          mcview_eof=
          skin=gotar

          [Layout]
          output_lines=0
          left_panel_size=52
          top_panel_size=0
          message_visible=true
          keybar_visible=true
          xterm_title=true
          command_prompt=true
          menubar_visible=true
          free_space=true
          horizontal_split=false
          vertical_equal=true
          horizontal_equal=true

          [Misc]
          timeformat_recent=%b %e %H:%M
          timeformat_old=%b %e  %Y
          ftp_proxy_host=gate
          ftpfs_password=anonymous@
          display_codepage=UTF-8
          source_codepage=Other_8_bit
          autodetect_codeset=
          clipboard_store=
          clipboard_paste=

          [Colors]
          base_color=
          xterm-kitty=
          color_terminals=

          [Panels]
          show_mini_info=true
          kilobyte_si=false
          mix_all_files=false
          show_backups=true
          show_dot_files=true
          fast_reload=false
          fast_reload_msg_shown=false
          mark_moves_down=true
          reverse_files_only=true
          auto_save_setup_panels=false
          navigate_with_arrows=false
          panel_scroll_pages=true
          panel_scroll_center=false
          mouse_move_pages=true
          filetype_mode=true
          permission_mode=false
          torben_fj_mode=false
          quick_search_mode=2
          select_flags=6

          [Panelize]
          Find SUID and SGID programs=find . \\( \\( -perm -04000 -a -perm /011 \\) -o \\( -perm -02000 -a -perm /01 \\) \\) -print
          Find rejects after patching=find . -name \\*.rej -print
          Modified git files=git ls-files --modified
          Find *.orig after patching=find . -name \\*.orig -print
        '';
      };

      "/home/jr/.config/mpv/mpv.conf" = {
        text = ''
          hwdec=auto-safe
          vo=gpu
          profile=gpu-hq
          gpu-context=wayland # ; On wayland only
        '';
      };

      ".config/starship.toml" = {
        text = ''
          # Get editor completions based on the config schema
          "$schema" = 'https://starship.rs/config-schema.json'

          # Inserts a blank line between shell prompts
          add_newline = true

        '';
      };
    };
  
    # The state version is required and should stay at the version you
    # originally installed.
    home.stateVersion = "25.11";
  };


  # Bootloader.
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;

  system.autoUpgrade.channel = "https://nixos.org/channels/nixos-unstable";

  # Enable networking
  networking.hostName = "nixos";
  networking.networkmanager.enable = true;
  #networking.nameservers = [ "94.140.14.14" "94.140.15.15" ];

  # Set your time zone.
  time.timeZone = "Europe/Copenhagen";

  # Select internationalisation properties.
  i18n.defaultLocale = "en_DK.UTF-8";

  i18n.extraLocaleSettings = {
    LC_ADDRESS = "da_DK.UTF-8";
    LC_IDENTIFICATION = "da_DK.UTF-8";
    LC_MEASUREMENT = "da_DK.UTF-8";
    LC_MONETARY = "da_DK.UTF-8";
    LC_NAME = "da_DK.UTF-8";
    LC_NUMERIC = "da_DK.UTF-8";
    LC_PAPER = "da_DK.UTF-8";
    LC_TELEPHONE = "da_DK.UTF-8";
    LC_TIME = "da_DK.UTF-8";
  };

  # Enable the KDE Plasma Desktop Environment.
  services.displayManager.sddm.enable = true;
  services.displayManager.sddm.wayland.enable = true;
  services.displayManager.defaultSession = "hyprland-uwsm";
  programs.hyprland.enable = true;
  programs.uwsm.enable = true;
  programs.hyprland.withUWSM = true;
  # services.xserver.enable = true;
  programs.hyprland.xwayland.enable = true;
  environment.sessionVariables.NIXOS_OZONE_WL = "1";

  services.gvfs.enable = true;
  services.udisks2.enable = true;
  services.devmon.enable = true;

  # Virtualisation


  networking.firewall.interfaces.virbr0.allowedTCPPorts = [ 53 ];
  networking.firewall.interfaces.virbr0.allowedUDPPorts = [ 53 67 ];

  services.dnsmasq.enable = true;
  services.dnsmasq.settings = {
    bind-interfaces = true;
  };

  boot.extraModprobeConfig = "options kvm_intel nested=1";

  programs.virt-manager.enable = true;
  
  virtualisation = {
    libvirtd = {
      enable = true;
      qemu = {
        runAsRoot = true;
        swtpm.enable = true;
        ovmf = {
          enable = true;
          packages = [  ];
        };
      };
    };
    spiceUSBRedirection.enable = true;

  };

  # Configure console keymap
  console.keyMap = "dk-latin1";

  # Enable sound with pipewire.
  services.pulseaudio.enable = false;
  security.rtkit.enable = true;
  services.pipewire = {
    enable = true;
    alsa.enable = true;
    alsa.support32Bit = true;
    pulse.enable = true;
  };

  # Define a user account. Don't forget to set a password with ‘passwd’.
  users.users.jr = {
    isNormalUser = true;
    description = "JR";
    extraGroups = [ "libvirtd" "networkmanager" "wheel" ];
    packages = with pkgs; [
    ];
  };

  security.polkit.extraConfig = ''
    polkit.addRule(function(action, subject) {
      if (subject.isInGroup("wheel")) {
        return polkit.Result.YES;
      }
    })
  '';  

  # Enable automatic login for the user.
  services.displayManager.autoLogin.enable = true;
  services.displayManager.autoLogin.user = "jr";

  # Allow unfree packages
  nixpkgs.config.allowUnfree = true;

  services.mullvad-vpn.enable = true;
  services.mullvad-vpn.package = pkgs.mullvad-vpn;

  hardware.graphics = {
    enable = true;
    extraPackages = with pkgs; [
      intel-media-driver # For Broadwell (2014) or newer processors. LIBVA_DRIVER_NAME=iHD
      intel-vaapi-driver # For older processors. LIBVA_DRIVER_NAME=i965
    ];
  };
  environment.sessionVariables = { LIBVA_DRIVER_NAME = "iHD"; }; # Optionally, set the environment variable

  programs = {
    gamescope = {
      enable = true;
      capSysNice = true;
    };

    steam = {
      enable = true;
      # gamescopeSession.enable = true;
    };
    gamemode.enable = true;
    
  };
  hardware.steam-hardware.enable = true;

  fonts.packages = [ pkgs.nerd-fonts.fira-code];

  # List packages installed in system profile. To search, run:
  environment.systemPackages = with pkgs; [

    # Tools
    conky
    dig
    kdePackages.dolphin
    doublecmd
    exfat
    fastfetch
    file-roller
    git
    home-manager
    htop
    isoimagewriter
    kitty
    mc
    ntfs3g
    p7zip
    pavucontrol
    putty
    rpi-imager
    starship
    trezord
    trezor-suite
    trezor-udev-rules
    usbutils
    vscodium
    # xarchiver

    # Gaming 
    protonup-qt

    # Media
    aria2
    # libdrm
    # libva
    # libva1
    libva-utils
    # libva-vdpau-driver
    lux
    media-downloader
    svtplay-dl
    video-downloader
    vlc
    you-get
    yt-dlp

    # Web
    brave
    mullvad-browser

    # Hypr
    hyprlandPlugins.xtra-dispatchers
    hyprlang
    hyprnotify
    hyprpaper
    hyprpolkitagent
    hyprprop
    hyprutils
    syspower
    waytrogen
    wofi

  ];

  system.stateVersion = "25.11"; # Did you read the comment?

}